### ISSUE TITLE
error

### ISSUE THREAD

**Issue by estarossa0** [estarossa0/webserv#29]
https://github.com/estarossa0/webserv/blob/2c941ba45a1daae6bd64e2fd1f9b3670238bf37f/srcs/Response.cpp#L105
give a not found error on file cause file is not a directory
I added a perror() and this was the output

![image](https://user-images.githubusercontent.com/57002508/123812851-554e2c00-d8ec-11eb-84a5-8b1c7a8c27b4.png)

request: curl localhost/public/cgi/home.php

**Comment by zlayine** [comment]
I fixed it in the hotfix, need to merge the pull request

**Comment by estarossa0** [comment]
![image](https://user-images.githubusercontent.com/57002508/123813719-09e84d80-d8ed-11eb-92fd-c854a5eb6acf.png)
can you link the PR to the issue from here 
so this issue is close automatically when pr is merged

**Comment by estarossa0** [comment]
I did it

**Comment by zlayine** [comment]
Ty
