### ISSUE TITLE
binding on a non-existent host

### ISSUE THREAD

**Issue by ombhd** [estarossa0/webserv#52]
<img width="453" alt="Screen Shot 2021-07-01 at 10 20 46 AM" src="https://user-images.githubusercontent.com/54411060/124101362-2dc7a280-da57-11eb-87e0-9c6f34ac6545.png">

**Comment by estarossa0** [comment]
can you provide more information ? I don't get the issue

**Comment by ombhd** [comment]
you can re-generate the same bug with the same output by changing the host in the config file to this value `non-existent-host`

**Comment by estarossa0** [comment]
I think we should check on syntax
